// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package db

import (
	"context"
)

const getSession = `-- name: GetSession :one
SELECT id, name, code, created_by, max_participants, status, created_at FROM sessions WHERE id = ? LIMIT 1
`

func (q *Queries) GetSession(ctx context.Context, id int64) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedBy,
		&i.MaxParticipants,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
